easyaudit_utils/urls.py
from django.urls import path
from . import views

app_name = "easyaudit_utils"
urlpatterns = [
    path("events/index/", views.IndexView.as_view(), name="index"),
    path("events/crud/list/", views.CRUDEventListView.as_view(), name="crud_event_list"),
    path("events/login/list/", views.LoginEventListView.as_view(), name="login_event_list"),
    path("events/request/list/", views.RequestEventListView.as_view(), name="request_event_list"),
]

easyaudit_utils/models.py
# from django.db import models

# Create your models here.

easyaudit_utils/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, TemplateView

from easyaudit.models import CRUDEvent, LoginEvent, RequestEvent

from .mixins import PaginationMixin, UserDateSearchMixin


class IndexView(LoginRequiredMixin, UserDateSearchMixin, TemplateView):
    template_name = "easyaudit/index.html"


class CRUDEventListView(LoginRequiredMixin, PaginationMixin, UserDateSearchMixin, ListView):
    model = CRUDEvent
    paginate_by = 50


class LoginEventListView(LoginRequiredMixin, PaginationMixin, UserDateSearchMixin, ListView):
    model = LoginEvent  # TODO : Use Django-defender
    paginate_by = 50


class RequestEventListView(LoginRequiredMixin, PaginationMixin, UserDateSearchMixin, ListView):
    model = RequestEvent
    paginate_by = 50

easyaudit_utils/templates/easyaudit/_filters.html
{% load i18n %}
<form action="" class="form" method="GET">
  <div class="row">
    <div class="col-lg-11">
      <div class="row">
        <div class="col-lg-3">
          <div class="">
            <label for="user">{% trans "User" %}</label>
            <input type="text" name="user" id="user" class="form-control" value="{{ request.GET.user }}">
            <small class="text-muted">{% trans "User identifier" %}</small>
          </div>
        </div>
        <div class="col-lg-3">
          <div class="">
            <label for="date">{% trans "Date begin" %}</label>
            <input type="text" name="date" id="date" class="form-control" value="{{ request.GET.date }}">
            <small class="text-muted">{% trans "Format YYYY-MM-DD" %}</small>
          </div>
        </div>
        <div class="col-lg-3">
          <div class="">
            <label for="date2">{% trans "Date end" %}</label>
            <input type="text" name="date2" id="date2" class="form-control"  value="{{ request.GET.date2 }}">
            <small class="text-muted">{% trans "Format YYYY-MM-DD. This will be checked if there is a date begin" %}</small>
          </div>
        </div>
        <div class="col-lg-3">

        </div>
      </div>
    </div>
    <div class="col-lg-1">
      <button type="submit" class="btn btn-info btn-sm">
        <i class="fas fa-search"></i>
        {% trans "Filter" %}
      </button>
    </div>
  </div>
</form>

easyaudit_utils/templates/easyaudit/crudevent_list.html
{% extends 'base/banking_base.html' %}
{% load i18n humanize static %}
{% load easyaudit_utils %}

{% block content %}
<div id="ledger-account-list-app">
    <h2 class="mt-3">{% trans 'CRUD Events' %}</h2>

    {% include "easyaudit/_filters.html" %}
    <hr/>



  <div name="fade">
    <div v-show="list_ledger_accounts" class="">
        <table class="table table-bordered bg-white table-hover table-striped">
        <thead class="">
            <tr>
                <th>{% trans 'Date' %}</th>
                <th>{% trans 'Event Type' %}</th>
                <th>{% trans 'Object' %}</th>
                <th>{% trans 'Object Description' %}</th>
                <th>{% trans 'Changed Fields' %}</th>
                <th>{% trans 'User' %}</th>
            </tr>
        </thead>
        <tbody>
        {% for crud in object_list %}
        <tr>
            <td>{{ crud.datetime }}</td>
            <td>
              <span class=" badge
              {% if crud.is_create %}
              badge-success
              {% elif crud.is_update %}
              badge-warning
              {% elif crud.is_delete %}
              badge-danger
              {% elif crud.event_type == crud.M2M_CHANGE %}
              badge-info
              {% elif crud.event_type == crud.M2M_CHANGE_REV %}
              badge-secondary
              {% endif %}
              ">
                {{ crud.get_event_type_display }}
              </span>
            </td>
            <td>{{ crud.content_type|title }}</td>
            <td title="{{ crud.object_json_repr }}">{{ crud.object_repr }}</td>
            <td>
              {% json_load crud.changed_fields as changed_fields %}
              {% if changed_fields %}
                <p>
                  {% for k,v in changed_fields.items %}
                    <b class="mr-1">{{ k }} :</b>{{ v.0|easy_format }} => {{ v.1|easy_format }}<br>
                  {% endfor %}
                </p>
              {% endif %}
            </td>
            <td>{{ crud.user }}</td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="7">{% trans 'No CRUD event' %}</td>
        </tr>
        {% endfor %}
    </tbody>
    </table>

    {% include "libs/pagination.html" with page_obj=page_obj %}
    </div>
</div>


</div>
{% endblock %}

easyaudit_utils/templates/easyaudit/index.html
{% extends 'base/banking_base.html' %}
{% load i18n %}

{% block content %}
<h3>Audit</h3>
<div class="row">
  	<div class="col-lg-2">
  		<div class="bg-white rounded shadow-sm border p-2 text-center">
    		<a class="" href="{% url 'easyaudit_utils:login_event_list' %}"><i class="fas fa-sign-in-alt fa-3x"></i></a>
    		<h5 class="mt-2"> Login Events</h5>
    	</div>
   	</div>
   	<div class="col-lg-2">
    	<div class="bg-white rounded shadow-sm border p-2 text-center">
    		<a href="{% url 'easyaudit_utils:crud_event_list' %}"><i class="fas fa-pencil-alt fa-3x"></i></a>
    		<h5 class="mt-2">CRUD Events</h5>
    	</div>
    </div>
    <div class="col-lg-2">
    	<div class="bg-white rounded shadow-sm border p-2 text-center">
    		<a href="{% url 'easyaudit_utils:request_event_list' %}"><i class="fas fa-exchange-alt fa-3x"></i></a>
    		<h5 class="mt-2">Request Events</h5>
    	</div>
    </div>
  </p>
</div>
{% endblock %}

easyaudit_utils/templates/easyaudit/loginevent_list.html
{% extends 'base/banking_base.html' %}
{% load i18n humanize static %}

{% block content %}
<div id="ledger-account-list-app">
    <h2 class="mt-3">{% trans 'LOGIN Events' %}</h2>
    
    {% include "easyaudit/_filters.html" %}
    <hr/>

<div name="fade">
    <div v-show="list_ledger_accounts" class="">
        <table class="table table-bordered bg-white table-hover table-striped">
        <thead class="">
            <tr>
                <th>{% trans 'Date' %}</th>
                <th>{% trans 'Login Type' %}</th>
                <th>{% trans 'Username' %}</th>
                <th>{% trans 'User' %}</th>
                <th>{% trans 'Remote IP' %}</th>
            </tr>
        </thead>
        <tbody>
        {% for login in object_list %}
        <tr>
            <td>{{ login.datetime }}</td>
            <td>
              <span class=" badge
              {% if login.login_type == login.LOGIN %}
              badge-success
              {% elif login.login_type == login.LOGOUT %}
              badge-warning
              {% elif login.login_type == login.FAILED %}
              badge-danger
              {% endif %}
              ">
                {{ login.get_login_type_display }}
              </span>
            </td>
            <td>{{ login.username }}</td>
            <td>{{ login.user.email }}</td>
            <td>{{ login.remote_ip }}</td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="7">{% trans 'No Login Event' %}</td>
        </tr>
        {% endfor %}
    </tbody>
    </table>

    {% include "libs/pagination.html" with page_obj=page_obj %}
    </div>
</div>


</div>
{% endblock %}

easyaudit_utils/templates/easyaudit/requestevent_list.html
{% extends 'base/banking_base.html' %}
{% load i18n humanize static %}

{% block content %}
<div id="ledger-account-list-app">
    <h2 class="mt-3">{% trans 'REQUEST Events' %}</h2>
    
    {% include "easyaudit/_filters.html" %}
    <hr/>

<div name="fade">
    <div v-show="list_ledger_accounts" class="">
        <table class="table table-bordered bg-white table-hover table-striped">
        <thead class="">
            <tr>
                <th>{% trans 'Date' %}</th>
                <th>{% trans 'Method' %}</th>
                <th>{% trans 'URL' %}</th>
                <th>{% trans 'Query String' %}</th>
                <th>{% trans 'User' %}</th>
                <th>{% trans 'Remote IP' %}</th>
            </tr>
        </thead>
        <tbody>
        {% for request in object_list %}
        <tr>
            <td>{{ request.datetime }}</td>
            <td>
              <span class=" badge
                {% if request.method == 'GET' %}
                badge-info
                {% elif request.method == 'POST' %}
                badge-success
                {% elif request.method == 'OPTION' %}
                badge-warning
                {% elif request.method == 'PUT' %}
                badge-secondary
                {% elif request.method == 'DELETE' %}
                badge-danger
                {% endif %}
              ">
                {{ request.method }}
              </span>
            </td>
            <td>{{ request.url }}</td>
            <td>{{ request.query_string }}</td>
            <td>{{ request.user }}</td>
            <td>{{ request.remote_ip }}</td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="7">{% trans 'No Request Event' %}</td>
        </tr>
        {% endfor %}
    </tbody>
    </table>

    {% include "libs/pagination.html" with page_obj=page_obj %}
    </div>
</div>


</div>
{% endblock %}